# Docker Compose 
version: '3.3'

# Define services
services:
  # spring service
  spring:
    image: spring_app_rami
    ports:
      - "8020:8001" 
    container_name: spring_cont_rami
    depends_on:
      - database
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/store1?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: rami
      SPRING_DATASOURCE_PASSWORD: rami123
    networks:
      - spr_net

  # Database Service (Mysql)
  database:
    image: mysql:latest
    container_name: mysql_cont_rami
    volumes:
      - db_ams:/var/lib/mysql 
    restart: always
    environment:
      MYSQL_DATABASE: store1
      MYSQL_USER: rami
      MYSQL_PASSWORD: rami123
      MYSQL_ROOT_PASSWORD: root
    networks:
      - spr_net

  # phpmyadmin Service 
  phpmyadmin:
    image: phpmyadmin
    container_name: pmadmin_cont_rami
    depends_on:
      - database
    restart: always
    ports:
      - 8083:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - spr_net

# Dec
volumes:
  db_ams:

networks:
  spr_net:


